import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';

import Navbar from '../components/Navbar';
import Container from '../components/Container';

function Section({ children, bg }) {
  return (
    <li
      className={`${bg} flex font-bold items-center justify-center rounded-md text-md text-white shadow hover:shadow-md`}
    >
      {children}
    </li>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Rick And Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Container className="my-5 h-80">
          <ul className="grid grid-cols-3 gap-x-2 lg:gap-x-32 my-10 md:gap-x-16 sm:gap-x-5 ">
            <Section bg="bg-purple-600">
              <Link href="/episodes" passHref>
                <a className="py-3 w-full text-center" href=".">
                  Episodes
                </a>
              </Link>
            </Section>
            <Section bg="bg-purple-600">
              <Link href="/characters" passHref>
                <a className="py-3 w-full text-center" href=".">
                  Characters
                </a>
              </Link>
            </Section>

            <Section bg="bg-purple-600">
              <Link href="/locations" passHref>
                <a className="py-3 w-full text-center" href=".">
                  Locations
                </a>
              </Link>
            </Section>
          </ul>
        </Container>
      </main>

      <footer className="bg-purple-800 py-5 text-white">
        <Container>Footer Section</Container>
      </footer>
    </>
  );
}

/*
 * This function is called only at build time and pass return as props
 */
export async function getStaticProps() {
  const { data } = await axios('https://rickandmortyapi.com/api/');
  return {
    props: {
      data,
    },
  };
}
