import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Navbar from '../components/Navbar';
import Container from '../components/Container';

export default function Home({ data }) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Rick And Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Container className="my-5 h-80">
          <ul className="grid grid-cols-3 gap-x-2 lg:gap-x-32 my-10 md:gap-x-16 sm:gap-x-5 ">
            {data.map((character) => (
              <li key="" className="relative">
                <Link href={`/characters/${character.id}`} passHref>
                  <a className="text-center" href=".">
                    <div className="img-container">
                      <Image
                        width="300"
                        height="300"
                        src={character.image}
                        alt=""
                      />
                    </div>
                    <h1>{character.name}</h1>
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </Container>
      </main>

      <style jsx>{`
        .img-container {
          width: 100%;
        }
        h1 {
          display: flex;
          align-items: flex-end;
          justify-content: center;
          height: 100%;
          background: linear-gradient(0deg, #030303bb, transparent);
          width: 100%;
          position: absolute;
          top: 0;
          left: 0;
          color: #fff;

          font-size: 2rem;
          font-weight: bold;
        }
      `}</style>
    </>
  );
}

/*
 * This function is called only at build time and pass return as props
 */
export async function getServerSideProps() {
  const { data } = await axios('https://rickandmortyapi.com/api/character');
  if (!data.info) return { props: { data: {} } };

  const { count } = data.info;

  const randomId = [];

  for (let i = 0; i < 3; i += 1)
    randomId.push(Math.floor(Math.random() * (count - 1)));

  const { data: res } = await axios(
    `https://rickandmortyapi.com/api/character/${randomId.map(
      (id, i) => `${encodeURIComponent(id)}`,
    )}`,
  );

  return {
    props: {
      data: res,
    },
  };
}
